lib/cfp_web/router.ex
defmodule CfpWeb.Router do
  use CfpWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :visitor do
    plug CfpWeb.Plugs.EnsureNotAuthenticated
  end

  pipeline :user do
    plug CfpWeb.Plugs.EnsureAuthenticated
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  # Public tasks
  scope "/", CfpWeb do
    pipe_through [:browser]
    
    resources "/slack", SlackController, only: [:index, :create, :new]
  end

  # Unconnected tasks
  scope "/public", CfpWeb do
    pipe_through [:browser, :visitor]
    
    get "/", PublicController, :index
  end

  # Unconnected tasks
  scope "/auth", CfpWeb do
    pipe_through [:browser, :visitor]
    
    get "/:provider", AuthController, :request
    get "/:provider/callback", AuthController, :callback
    post "/:provider/callback", AuthController, :callback
  end

  scope "/private", CfpWeb do
    pipe_through [:browser, :user]
    
    get "/", GlobalController, :index
    delete "/signout", AuthController, :delete
  end

end

lib/cfp/application.ex
defmodule Cfp.Application do
  use Application

  # See https://hexdocs.pm/elixir/Application.html
  # for more information on OTP Applications
  def start(_type, _args) do
    import Supervisor.Spec

    # Define workers and child supervisors to be supervised
    children = [
      # Start the Ecto repository
      supervisor(Cfp.Repo, []),
      # Start the endpoint when the application starts
      supervisor(CfpWeb.Endpoint, []),
      # Start your own worker by calling: Cfp.Worker.start_link(arg1, arg2, arg3)
      # worker(Cfp.Worker, [arg1, arg2, arg3]),
    ]

    # See https://hexdocs.pm/elixir/Supervisor.html
    # for other strategies and supported options
    opts = [strategy: :one_for_one, name: Cfp.Supervisor]
    Supervisor.start_link(children, opts)
  end

  # Tell Phoenix to update the endpoint configuration
  # whenever the application is updated.
  def config_change(changed, _new, removed) do
    CfpWeb.Endpoint.config_change(changed, removed)
    :ok
  end
end

lib/cfp/repo.ex
defmodule Cfp.Repo do
  use Ecto.Repo, otp_app: :cfp

  @doc """
  Dynamically loads the repository url from the
  DATABASE_URL environment variable.
  """
  def init(_, opts) do
    {:ok, Keyword.put(opts, :url, System.get_env("DATABASE_URL"))}
  end
end

lib/cfp/slack.ex
defmodule Cfp.Slack do

  @moduledoc """
  Some tools to communicate with Slack !
  """

  @doc """
  Returns the URL of the slack workspace
  """
  def workspace_url do
    "https://#{workspace()}.slack.com"
  end

  @doc """
  Returns the workspace's name
  """
  def workspace do
    Application.get_env(:cfp, CfpWeb.Endpoint)[:slack_workspace]
  end

  @doc false
  defp token do
    Application.get_env(:cfp, CfpWeb.Endpoint)[:slack_token]
  end

  
end

lib/github/organization.ex
defmodule Github.Organization do

  def on_board?(id, token) do
    req =
      "/orgs/#{Github.organization}/teams"
      |> Github.process_url()
      |> HTTPoison.get([{"Authorization", "token #{token}"}])
    with {:ok, response} <- req,
	 {:ok, list} <- Poison.decode(response.body) do
      check_member(id, list, token)
    else
      _ -> false
    end
 
  end

  defp check_member(id, list, token) do
    case Enum.find(list, fn(elt) -> elt["name"] == Github.board end) do
      nil -> false
      team -> has_member(id, team, token)
    end
  end

  defp has_member(id, team, token) do
    req =
      team["url"] <> "/members"
      |> HTTPoison.get([{"Authorization", "token #{token}"}])
    with {:ok, response} <- req,
	 {:ok, list} <- Poison.decode(response.body) do
      Enum.any?(list, fn(elt) -> elt["id"] == id end)
    else
      _ -> false
    end
  end


end

lib/slack/invitation.ex
defmodule Slack.Invitation do

  @moduledoc """
  Define Changeset for Slack invitation
  """

  use Ecto.Schema
  import Ecto.Changeset

  embedded_schema do: field :email

  @doc """
  A changeset for email address (in Slack)
  """
  def changeset(invitation, params \\ %{}) do
    invitation
    |> cast(params, [:email])
    |> validate_required([:email])
    |> validate_format(:email, ~r/@/)
  end

  @doc """
  perform validation on user parameters
  """
  def perform(parameters) do
    change = changeset(%__MODULE__{}, parameters)
    if change.valid? do
      {:ok, {change, change.changes.email}}
    else
      {:error, {change, Util.pop_error(change)}}
    end
  end

end

lib/cfp_web/controllers/auth_controller.ex
defmodule CfpWeb.AuthController do
  use CfpWeb, :controller

  plug Ueberauth
  plug :put_layout, "public.html"

  def callback(%{assigns: %{ueberauth_failure: _fails}} = conn, _params) do
    conn
    |> put_flash(:error, "Auth failure")
    |> redirect(to: public_path(conn, :index))
  end

  def callback(%{assigns: %{ueberauth_auth: data}} = conn, _params) do
    token = data.credentials.token
    id = data.extra.raw_info.user["id"]
    is_admin = Github.Organization.on_board?(id, token)
    conn
    |> put_flash(:info, "Yes")
    |> redirect(to: global_path(conn, :index))
  end

  def request(conn, _params) do
    url = Ueberauth.Strategy.Helpers.callback_url(conn)
    IO.inspect(conn)
    render(conn, "request.html", callback_url: url)
  end

  def delete(conn, _params) do
    # To be filled
    conn
    |> redirect(to: public_path(conn, :index))
  end
  
end

lib/cfp_web/controllers/global_controller.ex
defmodule CfpWeb.GlobalController do
  use CfpWeb, :controller

  plug :put_layout, "global.html"

  def index(conn, _params) do
    render(conn, "index.html")
  end
  
end

lib/cfp_web/controllers/page_controller.ex
defmodule CfpWeb.PageController do
  use CfpWeb, :controller

  plug :put_layout, "public.html"

  def index(conn, _params) do
    render conn, "index.html"
  end

  
end

lib/cfp_web/controllers/public_controller.ex
defmodule CfpWeb.PublicController do
  use CfpWeb, :controller

  plug :put_layout, "public.html"

  def index(conn, _params) do
    render conn, "index.html"
  end

  
end

lib/cfp_web/controllers/slack_controller.ex
defmodule CfpWeb.SlackController do
  use CfpWeb, :controller

  plug :put_layout, "public.html"

  alias Slack.Invitation

  def index(conn, _params) do
    changeset = Invitation.changeset(%Invitation{})
    render(conn, "index.html", changeset: changeset)
  end

  def new(conn, params), do: index(conn, params)

  def create(conn, %{"invitation" => params }) do
    {changeset, flash, message} =
      case Invitation.perform(params) do
	{:ok, {change, email}} ->
	  case Slack.invite(email) do
	    {:ok, _} -> {change, :info, "Invitation envoyée"}
	    {:error, err} -> {change, :error, err}
	  end
	{:error, {change, error_message}} ->
	  {change, :error, error_message}
      end
    conn
    |> put_flash(flash, message)
    |> render("index.html", changeset: changeset)
  end
  
end

lib/cfp_web/views/auth_view.ex
defmodule CfpWeb.AuthView do
  use CfpWeb, :view
end

lib/cfp_web/views/error_view.ex
defmodule CfpWeb.ErrorView do
  use CfpWeb, :view

  def render("404.html", _assigns) do
    "Page not found"
  end

  def render("500.html", _assigns) do
    "Internal server error"
  end

  # In case no render clause matches or no
  # template is found, let's render it as 500
  def template_not_found(_template, assigns) do
    render "500.html", assigns
  end
end

lib/cfp_web/views/global_view.ex
defmodule CfpWeb.GlobalView do
  use CfpWeb, :view
end

lib/cfp_web/views/layout_view.ex
defmodule CfpWeb.LayoutView do
  use CfpWeb, :view
end

lib/cfp_web/views/public_view.ex
defmodule CfpWeb.PublicView do
  use CfpWeb, :view
end

lib/cfp_web/views/slack_view.ex
defmodule CfpWeb.SlackView do
  use CfpWeb, :view
end

lib/cfp_web/templates/layout/footer.html.eex
<footer>
  <a href="<%= slack_path @conn, :index %>">
    <div data-icon="ei-comment" data-size="m" class="icon"></div>
  </a>
  <a href="https://www.youtube.com/channel/UC-hC7y_ilQBq0QCa9xDu1iA">
    <div data-icon="ei-sc-youtube" data-size="m" class="icon"></div>
  </a>
  <a href="https://twitter.com/lille_fp">
    <div data-icon="ei-sc-twitter" data-size="m" class="icon"></div>
  </a>
  <a href="https://github.com/lillefp/cfp">
    <div data-icon="ei-sc-github" data-size="m" class="icon"></div>
  </a>
</footer>

lib/cfp_web/templates/layout/global.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
  </head>
  <%= render "header.html", assigns %>
  <body>
    <div class="error"><%= get_flash(@conn, :error) %></div>
    <div class="info"><%= get_flash(@conn, :info) %></div>
    <header>
      <a href="<%= public_path @conn, :index %>">
	Accueil
      </a>
    </header>
    <main class="main-content">
      <%= render @view_module, @view_template, assigns %>
    </main>

    <%= render "footer.html", assigns %>
    <script src="https://cdn.jsdelivr.net/npm/evil-icons@1.9.0/assets/evil-icons.min.js"></script>
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

lib/cfp_web/templates/layout/header.html.eex
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="description" content="">
<meta name="author" content="">


<link href="https://raw.githubusercontent.com/raphaelgoetter/KNACSS/master/css/knacss.css" rel="stylesheet">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/evil-icons@1.9.0/assets/evil-icons.min.css">
<link href="https://fonts.googleapis.com/css?family=Roboto:100,300,400,500,700,900" rel="stylesheet"> 

<link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
<title>Hello Cfp!</title>

lib/cfp_web/templates/layout/public.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
  </head>
  <%= render "header.html", assigns %>
  <body>
    <div class="error"><%= get_flash(@conn, :error) %></div>
    <div class="info"><%= get_flash(@conn, :info) %></div>
    <header>
      <a href="<%= public_path @conn, :index %>">
	Accueil
      </a>
    </header>
    <main class="splash">
      <%= render @view_module, @view_template, assigns %>
    </main>

    <%= render "footer.html", assigns %>
    <script src="https://cdn.jsdelivr.net/npm/evil-icons@1.9.0/assets/evil-icons.min.js"></script>
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

lib/cfp_web/templates/page/index.html.eex
<div>

  <h1 class="splash-title"><span>participer</span>.lillefp</h1>
  <p class="highlight-p">
    <strong>LilleFP</strong> est un événement récurrent de la scène Lilloise,
    qui a pour thématique l'usage et la présentation de technologies, de langages
    et d'outils <strong>beaux</strong> et <strong>bien pensés</strong>.<br />
    Cette application vous permet de soumettre des participations, pour être
    pro-actif dans la communauté !
  </p>
  
  <div class="aered">
    <a href="#button" class="std-button main-button with-icon">
      <div>
	<div data-icon="ei-sc-github" data-size="m" class="icon"></div>
	<span>Se connecter</span>
      </div>
    </a>
  </div>
  
</div>

lib/cfp_web/templates/page/slack.html.eex
<div>

  <h1 class="splash-title"><span><%= Cfp.Slack.workspace%></span>.slack</h1>
  <p class="highlight-p">
    N'hésitez pas à nous rejoindre sur <strong>Slack</strong>, c'est assez actif et
    l'ambiance est vraiment sympa ! (En toute objectivité.)
  </p>
  <a href="<%= Cfp.Slack.workspace_url %>" class="std-button main-button with-icon">
    <div>
      <div data-icon="ei-pointer" data-size="m" class="icon"></div>
      <span>Accéder au Slack</span>
    </div>
  </a>
  <div class="aered">
    <h2>Demander une invitation</h2>
    <form>
      <input type="email" placeholder="vous@domain.io">
      <input type="submit" value="Demander !">
    </form>
  </div>
</div>

lib/cfp_web/templates/slack/index.html.eex
<div>

  <h1 class="splash-title"><span><%= Slack.workspace%></span>.slack</h1>
  <p class="highlight-p">
    N'hésitez pas à nous rejoindre sur <strong>Slack</strong>, c'est assez actif et
    l'ambiance est vraiment sympa ! (En toute objectivité.)
  </p>
  <a href="<%= Slack.workspace_url %>" class="std-button main-button with-icon">
    <div>
      <div data-icon="ei-pointer" data-size="m" class="icon"></div>
      <span>Accéder au Slack</span>
    </div>
  </a>
  <div class="aered">
    <h2>Créer un compte sur le Slack</h2>
    <%= form_for @changeset, slack_path(@conn, :create), fn f -> %>
      <%= email_input f, :email, placeholder: "vous@eux.io" %>
      <%= submit "Demander !" %>
    <% end %>
  </div>
</div>